### ISSUE TITLE
Make cross-platform

### ISSUE THREAD

**Issue by kentcdodds** [esnunes/imagina#1]
In the README it indicates the only thing holding this back from working on windows is the use of `mv` [here](https://github.com/esnunes/imagina/blob/c22c7406c0f3f1152c5543290bc217748b6aacc2/lib/imagina.js#L85). I think we could use [this](https://www.npmjs.com/package/mv) and get this working cross-platform. Thoughts?

**Comment by kentcdodds** [comment]
Oh, also, I was surprised by the assertion that it should work for windows at all (except that one thing). How do I instruct windows users to get the other `brew` dependencies on their machines? Thanks :-)

**Comment by esnunes** [comment]
Hi Kent, thanks for being interested in making image cross platform. When I created this library I was in a rush to delivery a project, so I ended up not paying attention to cross-platform issues. I believe that the package you pointed out would perfectly work.

The requirements installed using `brew` are the `imagemagick` command line tool and the `jpeg` + `png` libraries. The last two ones are required in case you want to convert files from/to `jpeg` / `png`. I believe windows or the imagemagick packge for windows comes with these two and other additional libraries required to convert image files. You can find information about how to install imagemagick on windows [here](http://www.imagemagick.org/script/binary-releases.php#windows).

In case you get any trouble trying to make it cross-platform, let me know, it will be a pleasure to help you. I've also created a simple a connect middleware to automatically resize images [imagina-middleware](https://github.com/esnunes/imagina-middleware).

I'm sorry about the 0 test coverage and lack of documentation of `imagina-middleware`.

**Comment by kentcdodds** [comment]
Cool, I make a PR for this eventually. Thanks for the info!

**Comment by kentcdodds** [comment]
I no longer need this to be cross-platform, so I'll go ahead and close this. Thanks!
